services:
  db:
    image: mysql:8.0
    container_name: nestjs-mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mysql
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306

# データを永続化させるため
volumes:
  db-store: